name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    environment:
      name: publish
      url: https://pypi.org/p/sqlalchemy-sessionload
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.10"
          cache: true
      - name: Install dependencies
        run: pdm install --frozen-lock
      - name: Build
        run: pdm build
      - name: Publish
        run: pdm publish --no-build
